scanner:
    diff_only: False
    linter: flake8

pycodestyle:  # Valid if scanner.linter is pycodestyle
    max-line-length: 79
    ignore: []  # Errors and warnings to ignore
    exclude: []  # File path patterns to exclude
    count: False
    first: False
    show-pep8: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: []
    select: []

flake8:  # Valid if scanner.linter is flake8
    max-line-length: 79
    ignore: []
    exclude: ["tests/test_exercise.py"]
    count: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: ["src/exercise.py"]
    select: []


no_blank_comment: False 
descending_issues_order: False  
only_mention_files_with_errors: True 

message: 
    opened:  
        header: "# :wave: Hi!\nI an a bot created to help you fix the syntax and style errors in your programming assignments. I will scan your code each time you submit (and re-submit) your program and create a list of necessary corrections.\n\nMy friend **GitHub Action Bot** will also be commenting here. He will notify you of any logic, formatting, or runtime errors in your program. Those will be a little harder to find, but he will point you in the right direction.\n\nYou may want to watch this [video](https://youtu.be/gdc-SYhRFCM) our creator made. It demonstrates how we will help you fix the errors in your programming assignment.\n\n## :pencil: To-do List:\n- [ ] Open both ```repl.it``` and this Feedback conversation side-by-side on your computer.\n- [ ] Read our bot comments here, and make a few small changes to your program in ```repl.it```.\n- [ ] After each small change you make, resubmit your file from ```repl.it```.\n- [ ] Wait for both bots to scan your new code.\n- [ ] We will make new comments directing you to fix more errors, -or- letting you know your program is free from errors.\n\n## :clipboard: Syntax/style errors to correct:"
        footer: ""
    updated: 
        header: "# :clipboard: Syntax/style errors to correct:"
        footer: ""
    no_errors: ""
