scanner:
    diff_only: False  
    linter: flake8

pycodestyle:  # Valid if scanner.linter is pycodestyle
    max-line-length: 79
    ignore: []  # Errors and warnings to ignore
    exclude: []  # File path patterns to exclude
    count: False
    first: False
    show-pep8: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: []
    select: []

flake8:  # Valid if scanner.linter is flake8
    max-line-length: 127
    ignore: []
    exclude: []
    count: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: []
    select: []

no_blank_comment: True  # If True, no comment is made on PR without any errors.
descending_issues_order: False 
only_mention_files_with_errors: True  # If False, a separate status section for each file is made in the comment.

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "# Hi! I'll be scanning your code for syntax and style errors each time you submit (commit/push) your assignment.
        footer: ""
    updated:  # Messages when a PR is updated
        header: "#Hi!\n\nWhat's your name?"
        footer: "```print("meow")```"
    no_errors: "There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: "
