scanner:
    diff_only: True
    linter: flake8

flake8:
    max-line-length: 120  # Default is 79 in PEP 8
    ignore:  # Errors and warnings to ignore
        - E266
        - E303
        - E128
        - E701
        - W504
        
message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: ""
        footer: ""
    updated:  # Messages when a PR is updated
        header: "meow"
        footer: "meow"
    no_errors: "There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: "
